- hosts: docker
  roles:
          - role: suzuki-shunsuke.docker_ce_centos
            docker_centos_state: started
            docker_centos_enabled: true
            docker_centos_users:
                    - vagrant
            become: true
